#if 0
TBL_MAJOR_VERSION = 2
TBL_MINOR_VERSION = 5
TBL_VERSION     = $(TBL_MAJOR_VERSION).$(TBL_MINOR_VERSION)
#endif
#define TBL_MAJOR_VERSION 2
#define TBL_MINOR_VERSION 5
#define TBL_VERSION "2.5"

